name: Run Python Tests

on: [ push ]

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Python ${{ matrix.python-version }}
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install pytest pytest-md pytest-emoji
        
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true

